# Generated by Django 4.2.7 on 2023-12-02 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_plateforme_service_remove_achat_plateforme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='plateforme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.plateforme'),
        ),
    ]
