# Generated by Django 4.2.7 on 2023-12-02 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_achat_plateforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
