# Generated by Django 4.2.7 on 2023-12-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_emploi_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
